---
- name: Create traefik directory
  file: 
    path: "{{ VAR_TRAEFIK_DIR }}"
    recurse: yes
    state: directory

- name: Create traefiki ssl directory
  file:
    path: "{{ VAR_TRAEFIK_SSL_DIR }}"
    recurse: yes
    state: directory

- name: Start traefik container
  containers.podman.podman_container:
    name: traefik
    image: traefik:latest
    pull: yes
    state: started
    expose:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /home/saihtam/cvols/traefik/:/etc/traefik/
      - "{{ VAR_TRAEFIK_DIR }}:/etc/traefik"
      - "{{ VAR_TRAEFIK_SSL_DIR }}:/etc/traefik/ssl/"
