---
- name: Create traefik directory
  file:
    path: "{{ VAR_TRAEFIK_DIR }}"
    recurse: yes
    state: directory

- name: Create traefiki ssl directory
  file:
    path: "{{ VAR_TRAEFIK_SSL_DIR }}"
    recurse: yes
    state: directory

- name: Copy static config file
  copy:
    src: traefik.yaml
    dest: "{{ VAR_TRAEFIK_DIR }}"
    owner: root 
    group: root
    mode: '0644'

- name: Create dynamic config from template
  template:
    src: traefik-dynamic.yml.j2
    dest: "{{ VAR_TRAEFIK_DIR }}/config/test.yml"
    owner: root
    group: root
    mode: '0644'

- name: Pull latest traefik image
  containers.podman.podman_image:
    name: traefik:latest

- name: Start traefik container
  containers.podman.podman_container:
    name: traefik
    image: traefik:latest
    state: started
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "{{ VAR_TRAEFIK_DIR }}:/etc/traefik/:Z"
      - "{{ VAR_TRAEFIK_SSL_DIR }}:/etc/traefik/ssl/:Z"
  register: container

- name: Create new systemd file
  shell: podman generate systemd --name traefik > /etc/systemd/system/container-traefik.service
  when: container.changed

- name: restart container with systemd
  systemd:
    state: restarted
    daemon_reload: yes
    name: container-traefik
  when: container.changed
