global:
  checkNewVersion: true

log:
  #level: "DEBUG"
  level: "ERROR"
  filePath: "/etc/traefik/log-file.log"

accessLog:
  filePath: "/etc/traefik/log-access.log"
  bufferingSize: 100

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: ":443"

providers:
  file:
#    directory: /etc/traefik/config
    filename: /etc/traefik/config/traefik-dynamic.yml
    watch: true
